cdn_profile_name = "scg-uofacommoninfra-npd-west-cdn"
cdn_profile_rg_name = "scg-uofa-prd-uofacommoninfra"
app_static_blob_name = "scguofatesttfprdstatic.z22.web.core.windows.net"
app_static_blob_rg_name = "scg-uofa-prd-terraform-nist"
cdn_endpoint_name = "cdnendpointname1"